[pytest]
# 1. הגדרות הרצה קבועות (חוסך הקלדה בטרמינל)
addopts = -v --alluredir=allure-results

# 2. איפה לחפש את הטסטים? (מאיץ את הסריקה של Pytest)
testpaths = 
    tests

# 3. הגדרת משפחות טסטים (מונע אזהרות בטרמינל)
markers =
    web: Tests related to Web UI
    api: Tests related to API endpoints
    db: Tests related to Database integration