[pytest]
# 1. הגדרות הרצה קבועות (חוסך הקלדה בטרמינל)
addopts = -v --alluredir=allure-results

# 2. איפה לחפש את הטסטים? (מאיץ את הסריקה של Pytest)
testpaths = 
    tests
# 3. איך לקרוא לטסטים? (מאיץ את זיהוי הטסטים)
python_files = test_*.py

markers =
    web: Web tests (Playwright)
    api: API tests (json-server)
    mobile: Mobile tests (Appium)
    db: Database tests (SQLite)
    e2e: End-to-end tests
    integration: Cross-layer integration tests
    use_ai: Run AI error analysis on failure